version: "2"
linters:
  enable:
    - bodyclose
    - exhaustive
    - gocritic
    - gosec
    - nilerr
    - unparam
  settings:
    errcheck:
      exclude-functions:
        - (net/http.ResponseWriter).Write
        - (*compress/gzip.Reader).Close
        - (*os.File).Close
        - (io.Closer).Close
        - (*net/http.Response).Body.Close
        - os.RemoveAll
        - fmt.Fprintf
        - fmt.Fprint
    exhaustive:
      default-signifies-exhaustive: true
    gosec:
      excludes:
        - G204
        - G107
        - G304
        - G301
        - G306
        - G302
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - gosec
        path: _test\.go
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
